### PR TITLE
fix(ntuples): x data from 0 - nbPoints

### LINKED ISSUE #47: XYData and X values
I think we could have always for X a value between 0 and Nb points

image

similar to what bruker generates

### PR DESCRIPTION
**Pull request by jobo322**
close: #47

### CODE REVIEW

File: demo/bruker-to-jcamp.ts [hunk 1]
```diff
@@ -0,0 +1,93 @@
+import { groupByExperiments, convertFileList } from 'brukerconverter';
```
Comment (lpatiny) [inline demo/bruker-to-jcamp.ts:1]: Should it be a testcase ?

File: src/creatorNtuples.ts [hunk 2]
```diff
@@ -111,9 +111,6 @@ export default function creatorNtuples(
         header += `${xData[point]}, ${yData[point]}\n`;
       }
     } else if (options.isXYData) {
-      const firstX = xData[0];
-      const lastX = xData[xData.length - 1];
-      const deltaX = (lastX - firstX) / xData.length;
```
Comment (lpatiny) [inline src/creatorNtuples.ts:116]: Not sure if this error was anywhere else but it should have been devided by (xData.length-1) seems to me.
